// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwtvixeoxmbusuyeiwqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3dHZpeGVveG1idXN1eWVpd3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzQ5OTQsImV4cCI6MjA2NjUxMDk5NH0.eZxUOnEJPRs1_lvZbGqFX4C-g5vjQ3b88TLMV6vUGz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);